# Generated by Django 3.0.5 on 2020-06-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='사용자명')),
                ('useremail', models.EmailField(max_length=128, verbose_name='사용자 이메일')),
                ('password', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('register_dttm', models.DateField(auto_now_add=True, verbose_name='가입날짜')),
            ],
            options={
                'verbose_name': '띵동 사용자',
                'verbose_name_plural': '띵동 사용자',
                'db_table': 'user_define_fuser_table',
            },
        ),
    ]
